#
# SPDX-FileCopyrightText: Â© 2020-2024 Serpent OS Developers
#
# SPDX-License-Identifier: MPL-2.0
#
name        : docker
version     : 28.0.4
release     : 6
homepage    : https://www.docker.com
upstreams   :
    - https://github.com/docker/cli/archive/refs/tags/v28.0.4.tar.gz : 09b41aa5ff656bc135feb80cb9b73c70aeba099ef9756c3cef7bcb2eb3c98ba6
summary     : The open-source application container engine
description : |
    The open-source application container engine. This contains the docker cli.
license     :
    - Apache-2.0
networking  : yes
builddeps   :
    - binary(go)
    - binary(go-md2man)
rundeps     :
    - binary(dockerd)
    - docker-buildx
setup       : |
    mkdir -p src/github.com/docker/
    ln -s ${PWD} src/github.com/docker/cli
build      : |
    cd src/github.com/docker/cli
    export GOPATH=${PWD}
    export GO111MODULE=auto

    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external"

    # Git commit corresponding to the version tag
    export GITCOMMIT=$(git ls-remote https://github.com/docker/cli.git refs/tags/v%(version)^{} | awk '{print $1}')
    export DOCKER_GITCOMMIT=${GITCOMMIT}

    # Docker is meant to be built inside a container and will exit with an error if this isn't set.
    export DISABLE_WARN_OUTSIDE_CONTAINER=1

    # build docker-cli
    %make dynbinary \
        VERSION=%(version) \
        PLATFORM="Docker Engine - Community"

    # man pages
    make manpages
install    : |
    # docker-cli
    %install_exe build/docker-linux-amd64 %(installroot)/%(bindir)/docker

    # man pages
    %install_file man/man1/*.1 -t %(installroot)/%(mandir)/man1
    %install_file man/man5/*.5 -t %(installroot)/%(mandir)/man5

    # completions
    %install_file contrib/completion/bash/docker %(installroot)/%(completionsdir)/docker
    %install_file contrib/completion/zsh/_docker %(installroot)/%(datadir)/zsh/site-functions/_docker
    %install_file contrib/completion/fish/docker.fish %(installroot)/%(datadir)/fish/vendor_completions.d/docker.fish

    # nano dockerfile syntax highlighting
    %install_file %(pkgdir)/Dockerfile.nanorc -t %(installroot)/%(datadir)/nano/
